### ISSUE TITLE
Create QR Code without external Service

### ISSUE THREAD

**Issue by RouL** [wbbaddons/Tims-2Factor-Auth#11]
For security reasons such QR Codes shouldn't be generated by an external webservice.

**Comment by TimWolla** [comment]
It is planned. I already talked with SoftCreatR about a possible QR-Code library for WCF. 

## 

Von: Markus Zhang
Gesendet: ‎Dienstag‎, ‎24‎. ‎September‎ ‎2013 ‎07‎:‎11
An: wbbaddons/Tims-2Factor-Auth

For security reasons such QR Codes shouldn't be generated by an external webservice.
